#!/usr/bin/env bash
# scripts/03-build-kernel.sh — Compile Linux 6.12.y for KrylixOS
# Wraps kernel/build-kernel.sh with VM-specific env setup
#
# Expected time: ~70 min on 2-core Fedora 43 VM
# Expected output: ~/rpmbuild/RPMS/x86_64/kernel-krylix-*.rpm
#
# Usage:
#   source .env.dev
#   bash scripts/03-build-kernel.sh

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo ""
echo "═══ Step 3: Build Kernel (Linux 6.12.y) ═══"
echo ""

# On VM: MOK key from /etc/pki/krylix/KrylixOS-dev.key (generated by vm-setup.sh)
# In CI: MOK_PRIVATE_KEY_PEM from GitHub Secret
if [[ -z "${MOK_PRIVATE_KEY_PEM:-}" ]]; then
    DEV_KEY="/etc/pki/krylix/KrylixOS-dev.key"
    if [[ -f "${DEV_KEY}" ]]; then
        export MOK_PRIVATE_KEY_PEM=$(cat "${DEV_KEY}")
        echo "[kernel] Using VM dev MOK key (not for production CI)"
    else
        echo "[kernel] ⚠  No MOK key — kernel will be UNSIGNED"
        echo "         Run .devcontainer/setup.sh to generate dev keys"
    fi
fi

export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-$(git log -1 --format=%ct 2>/dev/null || date +%s)}"

echo "[kernel] Kernel version will be auto-detected (6.12.y from kernel.org)"
echo "[kernel] CPUs available: $(nproc)"
echo "[kernel] RAM available:  $(free -h | awk '/^Mem:/{print $2}')"
echo "[kernel] SOURCE_DATE_EPOCH: ${SOURCE_DATE_EPOCH}"
echo ""

START=$(date +%s)
bash kernel/build-kernel.sh
END=$(date +%s)

echo ""
echo "[kernel] Compile time: $(( (END - START) / 60 )) min $(( (END - START) % 60 )) sec"
echo ""

# Show output
RPM_PATH=$(find ~/rpmbuild/RPMS -name "kernel-krylix-*.rpm" 2>/dev/null | head -1 || echo "")
if [[ -n "${RPM_PATH}" ]]; then
    echo "  ✓ Kernel RPM: ${RPM_PATH##*/}"
    echo "  Size: $(du -sh "${RPM_PATH}" | cut -f1)"
else
    echo "  ✗ Kernel RPM not found — check build output above"
    exit 1
fi

echo ""
echo "  Proceed to: bash scripts/04-build-iso.sh"
